### ISSUE TITLE
Fail2ban and iptables issue

### ISSUE THREAD

**Issue by emrahkayihan1985** [hestiacp/hestiacp#1371]
### In a few words, please describe the issue that you're experiencing:
In the web interface, when fail2ban is stopped iptables is also stopped.

<img src="https://i.ibb.co/6Fz6mdX/asdasd.gif"  />

### Operating system:

Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.0

**Comment by Pleskan** [comment]
That's normal behaviour, fail2ban is not working without iptables, it is based on IP tables .

**Comment by ghost** [comment]
Hi @emrahkayihan, thanks for your report -- this has been fixed for the next service release. I'll go ahead and close this report now, if you have any questions or concerns please let us know.

**Comment by emrahkayihan1985** [comment]
The problem still persists.

Operating system:
Ubuntu 20.04 LTS
Hestia Control Panel version:
1.3.2

@jaapmarcus

**Comment by jaapmarcus** [comment]
1.3.2 only contains bug fixes regarding php-fpm not deleted on template change. Changes to LE logging and an security fix. See changelog
