### ISSUE TITLE
Roundcube Deleted email stays in Inbox

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#174]
### Operating System (OS/VERSION):

Ubuntu 18.04.2

### HestiaCP Version:

Latest

### Installed Software (what you got with the installer):

nginx php-fpm

### Steps to Reproduce:

delete an email in roundcube

### Other Notes:

It grays the message out but does not move the email to the Trash. When I send an email it goes into the sent folder which is correct. Maybe a misconfiguration somewhere

**Comment by ioannidesalex** [comment]
I've had this issue only once. Go to Roundcube Settings,  Server Settings, Uncheck Flag the message for deletion instead of delete.

Please let us know how it goes.

**Comment by johnnyq** [comment]
that fixed it! although that shouldn't be the default behavior when a new email account is created.

**Comment by ioannidesalex** [comment]
Indeed. I currently have 8 Hestia servers and this issue has occured only at one server.

Needs more investigation.

**Comment by johnnyq** [comment]
thats interesting, i'm currently testing hestiacp to possibly use it for production. I'll spin up a few VMs and see of If can replicate, ill keep posted

**Comment by ioannidesalex** [comment]
Thanks! That will be very useful.

**Comment by ghost** [comment]
I've seen this behavior with Roundcube as well on one of my test VMs on Ubuntu 18.04.2 running the latest code from master. If need be I can help investigate/test later this week when I have more time.

**Comment by ioannidesalex** [comment]
That will be very useful. I tried to replicate this with several VMs but I wasn't able. It was only the first time I deployed an installation.

Without having this issue again it is very difficult to troubleshoot, so any feedback will be appreciated.

**Comment by johnnyq** [comment]
I spun up 4 more VMs with ubuntu 18.04.2 and have the same issue. I use proxmox and use proxmox's LXC Ubuntu container. I will try with a KVM VM and install via ubuntu 18.04.2 iso

**Comment by ScIT-Raphael** [comment]
@kristankenney It would be nice if you can find some time :).
@johnnyq Thanks for your tests, infact that kristankenney also had this issue, we will search for a solution.

**Comment by ioannidesalex** [comment]
Actually I remembered now, after reading @johnnyq comment! That one time I had this issue was a Proxmox Installation and it isn't the only Proxmox installation I have.

**Comment by johnnyq** [comment]
did another test on debian 9 LXC proxmox container, does the same thing. Although Debian 9 roundcube is an older version of roundcube. I noticed because it uses the gradient larry theme while the new one uses the flat larry theme. I thought hestia updates to the latest roundcube through roundcube's repo. I could be wrong. It's irrelevant as the delete issue still exists with deb9 lxc. I will try with an actual KVM VM with ubunu iso next

**Comment by ioannidesalex** [comment]
As far as I know Hestia uses the default OS packages for Roundube. However, it updates phpMyAdmin to the latest version.

Please let us know how it goes with KVM.

Thanks a lot cornyour feedback.

**Comment by johnnyq** [comment]
Oh okay thats makes sense. I will keep posted with the KVM test

**Comment by ghost** [comment]
If you have been able to reproduce this again, can you please modify the Roundcube configuration file on the server to reflect the following changes?

`nano /etc/roundcube/config.inc.php`

Locate the following line:
`$rcmail_config['flag_for_deletion'] = 'Purge';`

Change it to:
`$rcmail_config['flag_for_deletion'] = 'false';`

Then try to delete a message again.

**Comment by johnnyq** [comment]
@kristankenney I modified the var from Purge to false and then rebooted. Its still doing the same thing. Also I spun up an ubuntu 18.04.2 KVM VM via ubuntu 18.04.2 server iso and im getting the same results

**Comment by ScIT-Raphael** [comment]
@johnnyq please try to create a new mailbox, the settings could be still saved in existing users.

**Comment by ScIT-Raphael** [comment]
The way suggested from @kristankenney works on my side, I implemented this for all new configurations with the following commit: https://github.com/hestiacp/hestiacp/commit/8b542074c7812ef54894ceded5991669848868a6

**Comment by johnnyq** [comment]
@ScIT-Raphael Still not working its still staying in the inbox marked as deleted but not moving it to the trash. Although when I logout of webmail then log back in the messages marked deleted go away, but dont end up in the trash. Ill recreate the container with your latest patch and see what happens

**Comment by johnnyq** [comment]
Okay I just rebuilt the VM Container and its still doing the same thing. I wonder if there's another option that we may be missing. Ill look too

**Comment by ScIT-Raphael** [comment]
It should not; we've tested this on around 4 or 5 different systems. Maybe it's a small typo, try to set it like the following example:
`$rcmail_config['flag_for_deletion'] = false;`

**Comment by johnnyq** [comment]
It worked!! i had 'false' instead of just false maybe that caused it

**Comment by ScIT-Raphael** [comment]
perfet that it worked, we will push this way with the next updates. Will close this issue for now.

**Comment by johnnyq** [comment]
I did a reinstall actually config.inc.php is the file that should be updated as main.inc.php does not exist

**Comment by ScIT-Raphael** [comment]
Please check the commit you've commented, main.inc.php will be renamed to config.inc.php during installation.
