### ISSUE TITLE
[BUG] Let's Encrypt domain validation failed

### ISSUE THREAD

**Issue by ayoubamine** [hestiacp/hestiacp#2176]
**Describe the bug**
Let's Encrypt SSL certificate doesn't work if the domain redirection is enabled.

Error message:
```
Error: Let's Encrypt validation status 400 (...). Details: Unable to update challenge :: authorization must be pending
```

**To Reproduce**
1. Add/Edit web domain.
2. Enable domain redirection (Redirect visitors to a custom domain or web address).
3. Enable SSL for this domain (Use Lets Encrypt to obtain SSL certificate).

**Expected behavior**
Enable SSL certificate and redirect visitors to the new domain.

**Screenshots**
<img width="480" alt="1" src="https://user-images.githubusercontent.com/30782991/136591134-ef994c7d-9aa1-40a1-9cdf-968feede21de.png">

<img width="329" alt="2" src="https://user-images.githubusercontent.com/30782991/136591301-15d50e76-8da4-4fdb-bfcc-ad479ccd4ae7.png">

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
v1.4.17

**Additional context**
I think that the `nginx.ssl.conf_redirect` overrides the `.well-known` location in the `nginx.ssl.conf_letsencrypt`, so the domain validation process failed.

`nginx.ssl.conf_redirect`:
```
return 301 https://...$request_uri;
```

`nginx.ssl.conf_letsencrypt`:
```
location ~ "^/\.well-known/acme-challenge/([-_A-Za-z0-9]+)$" {
    default_type text/plain;
    return 200 "...";
}
```

**Comment by johnnyq** [comment]
@ayoubamine I noticed this too we use 301 redirects on a few domains and subdomains. I was going to post about this a couple of weeks ago but you beat me to it ;-) Hopefully its an easy fix.

A quick temporary resolution for this is:

- Take off the 301 redirect
- Request new Cert
- Then re-enable the 301 Redirect

Although not ideal but it does work for now.

**Comment by johnnyq** [comment]
I had the same issue today with one of my Lets Encrypt sub domain redirects so it brought me back to this thread. 

Anyone figure out any alternative solution to this other than a manual intervention?

From my understanding a 301 is a hard redirect which there may not be a solution for this, but I may be wrong.

**Comment by vvcares** [comment]
As of my knw, this behaviour is technically correct    letsencrypt also follows your 301 & of course it failed.

**Comment by jaapmarcus** [comment]
Fixed

**Comment by wizdude** [comment]
i'm running v1.5.11 and still have this same issue now. i have to manually remove the redirection in order for this to work as expected.

from reading the thread above this issue should have been resolved already? but it appears the same problem has reoccurred.

**Comment by jaapmarcus** [comment]
Will add an automated test for it to see if it can be replicated

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2510

For renewal it should be working fine

Did you first change redirection and then attempt requesting SSL?

**Comment by jaapmarcus** [comment]
Haven't been able to "repoduce" the error on our testing server against the staging server. Allowing more requests then the default server.

**Comment by wizdude** [comment]
> Did you first change redirection and then attempt requesting SSL?

yes - i manually disabled the redirection and then enabled SSL (as i needed to add a new name) and then re-enabled redirection again.

that works - but it's really clunky. is there a way to implement the same procedure that's used with renewals when we are adding (or changing) SSL for redirections? would be nice to have that cleaned up. 

cheers :-)

**Comment by jaapmarcus** [comment]
I can see why my tests "works" 

https://github.com/hestiacp/hestiacp/blob/3ee1175e5aa9f35a8c1e4687568f0b84d9a837d7/bin/v-add-web-domain-redirect#L108-L115

Unless restart flag is present it doesn't restart nginx

**Comment by jaapmarcus** [comment]
```
@test "[ Redirect ] Add Domain redirect to other website" {
    run v-add-web-domain-redirect $user "redirect.$domain" "https://hestiacp.com" 301 "yes"
    assert_success
    refute_output
}

@test "[ Redirect ] Request new certificate for web {
    run v-add-letsencrypt-domain $user "redirect.$domain" ""
    assert_success
    refute_output
}

@test "[ Redirect ] Run renewal script for LE Redirected domain" {
    run v-update-letsencrypt-ssl
    assert_success
    refute_output
}
```
Following test script will fail so it is now only sorting out a solution...

**Comment by jaapmarcus** [comment]
Issue should be fixed on 8 April last year. Forgot to close the issue
