### ISSUE TITLE
[Bug] Ability to create same database user twice

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#3300]
### Describe the bug

It is causing issues with password changes and so on. We should probally disable this "feature" and check if the user name (user_xxx) allready exists on database creation.. 

### Tell us how to replicate the bug

Create 2 database with the same username 

Update 1 database password

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.6.x

### Operating system

N/A

**Comment by jaapmarcus** [comment]
Fixed

**Comment by SPEC1AL1ST** [comment]
Not fixed,
already have problem Error: DBUSER= already exists when i try to create second DB
v1.8.11

**Comment by jaapmarcus** [comment]
> Not fixed, already have problem Error: DBUSER= already exists when i try to create second DB v1.8.11

That is the reason why this fix is here it should be allowed...
