### ISSUE TITLE
[Bug] sFTP doesn't work | wrong line in sshd_config

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#4912]
### Describe the bug

I rolled in a few servers in last 3 days and almost all of them failed to connect over sFTP for any user's made inside HestiaCP. The SSH would work for users that I change shell for... but sFTP would login and disconnect immediately. 

After some playing around I noticed **line 116** of  `/etc/ssh/sshd_config` says 

`Subsystem sftp internal-sftp-server`
Deleting the part '-server' from it fixed the sFTP connections. Screenshot attached for reference.

So it needs to read 
`Subsystem sftp internal-sftp`

Can the devs pls double check and fix this ASAP. pls

![Image](https://github.com/user-attachments/assets/825a31f7-dc9b-4faf-866d-f090d38c84de)

### Tell us how to replicate the bug

 **line 116** of  `/etc/ssh/sshd_config` 
Replace `Subsystem sftp internal-sftp-server`
with `Subsystem sftp internal-sftp`

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.9.3

### Operating system

Debian 12

### Log capture

```shell

```

**Comment by ufo56** [comment]
This bug is still not fixed!

**Comment by pavlozt** [comment]
We see that the bug is fixed, merged ( https://github.com/hestiacp/hestiacp/pull/4873) ,  but version 1.9.4 is not released yet - https://github.com/hestiacp/hestiacp/blob/4438939f2f4980ce7a96b7954b9a88c55bbe4127/install/upgrade/versions/1.9.4.sh#L26

**Comment by HungNth** [comment]
This bug is still not fixed; it took me 30 minutes when I was a beginner learning to use hesticcp.

**Comment by matbcvo** [comment]
I can confirm this issue still exists on a fresh Ubuntu 24.04 LTS installation with HestiaCP v1.9.4.

`/etc/sshd/sshd_config` contains:
```bash
# override default of no subsystems
Subsystem sftp internal-sftp-server
```
After changing it to:
```bash
# override default of no subsystems
Subsystem sftp internal-sftp
```
and restarting the SSH service, I’m able to connect via SFTP.
