### ISSUE TITLE
[Bug] root is not possible to connect via SFTP using keyfile

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#5024]
### Describe the bug

When i want to connect as root using keyfile, I always got this error:

```
FATAL ERROR: Received unexpected end-of-file from SFTP server
Error: Unable to connect to the server
```

the problem is in the '/etc/ssh/sshd_config' 

it should be:
`Subsystem sftp internal-sftp`

instead of:
`Subsystem sftp internal-sftp-server`

because 'internal-sftp-server' is not a valid OpenSSH directive

### Tell us how to replicate the bug

1. login root via sftp using keyfile

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.9.3

### Operating system

Ubuntu LTS

### Log capture

```shell

```

**Comment by sahsanu** [comment]
This has been fixed in https://github.com/hestiacp/hestiacp/pull/4873

**Comment by matbcvo** [comment]
I can confirm this issue still exists on a fresh Ubuntu 24.04 LTS installation with HestiaCP v1.9.4.

`/etc/sshd/sshd_config` contains:
```bash
# override default of no subsystems
Subsystem sftp internal-sftp-server
```
After changing it to:
```bash
# override default of no subsystems
Subsystem sftp internal-sftp
```
and restarting the SSH service, I’m able to connect via SFTP.

**Comment by sahsanu** [comment]
> I can confirm this issue still exists on a fresh Ubuntu 24.04 LTS installation with HestiaCP v1.9.4.

The issue was fixed in #4873, however, that PR was not included in Hestia 1.9.4.

**Comment by SKJoy** [comment]
> I can confirm this issue still exists on a fresh Ubuntu 24.04 LTS installation with HestiaCP v1.9.4.
> 
> `/etc/sshd/sshd_config` contains:
> 
> # override default of no subsystems
> Subsystem sftp internal-sftp-server
> After changing it to:
> 
> # override default of no subsystems
> Subsystem sftp internal-sftp
> and restarting the SSH service, I’m able to connect via SFTP.

Just installed `HestiaCP` and the **BUG** still exists! Applying this *patch* fixed it.

**Comment by sahsanu** [comment]
@SKJoy the patch was merged but not included in version 1.9.4. If you only edited `/etc/ssh/sshd_config` file, it will happen again.
