### ISSUE TITLE
Bug: Installation with --nginx no flag fails due to held hestia package.

### ISSUE THREAD

**Issue by mckaygerhard** [hestiacp/hestiacp#824]
### In a few words, please describe the issue that you're experiencing:

hestiacp panel doe snot install .. debian 9

### What steps did you take when the issue occured? 
1. `wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh`
2. `bash hst-install.sh -a yes -n no -w yes -o no -g yes -m yes  -q yes -s srv1.mydomain.com -e mycorr@gmail.com -p mypasswd -y`

### Expected behavior:

installer

### Does this issue always occur, or is it intermittent?

currently alwasy happened

### Operating system distribution and release:

Debian 9

### Which version of Hestia Control Panel is currently installed?

N/A

### Which branch are you using?

release

### When did this issue occur? After a clean installation, or after an upgrade?

install step

### Which of the following web server configurations are you using?

   - Apache Web Server
   - PHP-FPM Application Server
   - Bind DNS Server
   - Exim Mail Server + ClamAV + SpamAssassin
   - Dovecot POP3/IMAP Server
   - MariaDB Database Server
   - PostgreSQL Database Server
   - Vsftpd FTP Server
   - Firewall (Iptables) + Fail2Ban Access Monitor

### In order to better assist, please post any relevant log information below:

```
(*) Configuring system settings...
(*) Configuring Hestia Control Panel...
cp: cannot stat '/usr/local/hestia/install/deb/sudo/admin': No such file or directory
chmod: cannot access '/etc/sudoers.d/admin': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/hestia': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/packages': No such file or directory
sed: can't read /usr/local/hestia/data/packages/*.pkg: No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/unassigned/index.html': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/skel/document_errors/*': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/firewall': No such file or directory
(*) Generating default self-signed SSL certificate...
hst-install-debian.sh: line 1110: /usr/local/hestia/bin/v-generate-ssl-cert: No such file or directory
(*) Adding SSL certificate to Hestia Control Panel...
sed: -e expression #1, char 3: unexpected `,'
sed: -e expression #1, char 1: unknown command: `,'
cp: cannot stat '/usr/local/hestia/install/deb/ssl/dhparam.pem': No such file or directory
(*) Configuring Apache Web Server...
cp: cannot stat '/usr/local/hestia/install/deb/apache2/apache2.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/apache2/status.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/apache2': No such file or directory
hst-install-debian.sh: line 1183: /etc/apache2/sites-available/default: No such file or directory
hst-install-debian.sh: line 1184: /etc/apache2/sites-available/default-ssl: No such file or directory
hst-install-debian.sh: line 1186: /etc/apache2/suexec/www-data: No such file or directory
Failed to start apache2.service: Unit apache2.service not found.
Error: apache2 start failed
```

**Comment by nerv55** [comment]
Same here, I reproduce this issue in debian 9

**Comment by mckaygerhard** [comment]
the problem are the stupid sury repos! that guy are a fantoche bad packager!

i'm able to install by deactivating multi php and php special flags.. but now apache2 fails:

```
-
Now installing Hestia Control Panel and all required dependencies.
NOTE: This process may take 10 to 15 minutes to complete, please wait... 
-
(*) Configuring system settings...
(*) Configuring Hestia Control Panel...
(*) Generating default self-signed SSL certificate...
(*) Adding SSL certificate to Hestia Control Panel...
(*) Configuring NGINX...
(*) Configuring Apache Web Server...
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
Error: apache2 start failed
root@srv1:/tmp/hestiacp# systemctl status apache2.service
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-05-21 22:21:05 CDT; 30s ago
  Process: 25856 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)

May 21 22:21:05 srv1.dom.com systemd[1]: Starting The Apache HTTP Server...
May 21 22:21:05 srv1.dom.com apachectl[25856]: AH00534: apache2: Configuration error: No MPM loaded.
May 21 22:21:05 srv1.dom.com apachectl[25856]: Action 'start' failed.
May 21 22:21:05 srv1.dom.com apachectl[25856]: The Apache error log may have more information.
May 21 22:21:05 srv1.dom.com systemd[1]: apache2.service: Control process exited, code=exited status=1
May 21 22:21:05 srv1.dom.com systemd[1]: Failed to start The Apache HTTP Server.
May 21 22:21:05 srv1.dom.com systemd[1]: apache2.service: Unit entered failed state.
May 21 22:21:05 srv1.dom.com systemd[1]: apache2.service: Failed with result 'exit-code'.
```

now trying withoout apache2 to see if theres something into:

```
Now installing Hestia Control Panel and all required dependencies.
NOTE: This process may take 10 to 15 minutes to complete, please wait... 
-
(*) Configuring system settings...
(*) Configuring Hestia Control Panel...
(*) Generating default self-signed SSL certificate...
(*) Adding SSL certificate to Hestia Control Panel...
(*) Configuring NGINX...
(*) Configuring PHP-FPM...
(*) Configuring PHP...
(*) Configuring Vsftpd server...
(*) Configuring MariaDB database server...
(*) Installing phpMyAdmin version v5.0.1...
(*) Configuring PostgreSQL database server...
ALTER ROLE
(*) Configuring Bind DNS server...
(*) Configuring Exim mail server...
(*) Configuring Dovecot POP/IMAP mail server...
(*) Installing ClamAV anti-virus definitions.../
(*) Configuring SpamAssassin...
(*) Configuring Roundcube webmail client...
(*) Configuring fail2ban access monitor...
/dev/sda1 [/]: group quotas turned on
/dev/sda1 [/]: user quotas turned on
```

**Comment by jaapmarcus** [comment]
Did you run 

`apt-get update && apt-get dist-upgrade 

For quotas you are missing some kernel parts see https://www.digitalocean.com/community/questions/enable-quota-ubuntu-16-04-error to fix it. Don't know if it works on Debian...

**Comment by ScIT-Raphael** [comment]
First of all, @mckaygerhard :
> the problem are the stupid sury repos! that guy are a fantoche bad packager!

We do not blame anyone here, @oerdnj does a huge job for free, if you think you can do it better, please provide us a link to your repository. It is the same like for hestia: It is free to use and we give our best to make it as stable as possible, but there are always issues that may come up - we are all humans that can make mistakes.

Possible duplicate in our forum: https://forum.hestiacp.com/t/error-on-installation-debian-10/901

Going to check in a few minutes what's failing, a issue with the sury repository is possible - the installation fails on apt-get install $software. Will report back in a bit.

**Comment by ScIT-Raphael** [comment]
First Update: I've tested the default installation of hestia on debian 9 and 10 on Hetzner Cloud Services and can't find any issue - both installations went properly trough, the system is up and running. I'm going no to test for problems with your installation string.

**Comment by ScIT-Raphael** [comment]
Found out a issue that only shows up with using your specific installation string:
```
The following held packages will be changed:
  hestia
0 upgraded, 229 newly installed, 0 to remove and 0 not upgraded.
E: Held packages were changed and -y was used without --allow-change-held-packages.
Error: apt-get install failed
```

I currently try to find out why this happens, if you want to proceed your installation, please download the debian installer and adjust the following line: https://github.com/hestiacp/hestiacp/blob/69261bdffff9928fd04572fc532eb7ad47bdb5f1/install/hst-install-debian.sh#L834

Add --allow-change-held-packages behind the -y, also let us know if the installation then works properly.

**Also to confirm, the issue hangs together with the --nginx no flag you use there, as soon this flag is set to no, the hestia package get on held.**

**Comment by oerdnj** [comment]
@ScIT-Raphael Thanks for your kind words. JFTR the user in question has already shown abusive behavior in my issue tracker and has been on my block list for some time.

**Comment by ScIT-Raphael** [comment]
Hi @oerdnj 

Thanks for your reaction, information and welcome to hestia :)!

We have integrated your repository so we can provide multiphp support for our web stack. I would also like to thank you on behalf of Hestia and me personally for the great work you do with your Sury repository!

PS: Next beer's on us.

**Comment by jobetinfosec** [comment]
Hi,

I posted same issue in this post: https://forum.hestiacp.com/t/error-on-installation-debian-10/901

Today I've tried adding "--allow-change-held-packages behind the -y" to debian installer file, but setup keeps aborting...

Here's log content:

```
cat hst_install_backups/hst_install-220520200844.log
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  libxml2
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

Any clue?

Regards

**Comment by ScIT-Raphael** [comment]
Currently the easiest and most logical way: Enable nginx as frontend proxy for static files. Personaly I don't see any reason to not use it at all.

We'll try to debug and find a solution for the hestia package held problem - that's why the ticket here is still open, but this may take a while until we sorted it out :).

**Comment by jobetinfosec** [comment]
Hi,

I've tried to install only Nginx (without Apache) and everything went ok!

So the problem is the "nginx no" flag...

However I would need to install only Apache without Nginx...

I'll wait for your solution!

Thanks.

Regards

**Comment by ScIT-Raphael** [comment]
Usualy, you install both webservers, apache2 and nginx. Is there a specific reason why you need apache2 only?

**Comment by jobetinfosec** [comment]
Hi,

Actually I normally install only Nginx on my servers.

This time I need to install only Apache, as I'm buiding a monitoring server with Zabbix package, that requires Apache server.

Regards

**Comment by jaapmarcus** [comment]
https://www.zabbix.com/download?zabbix=5.0&os_distribution=ubuntu&os_version=18.04_bionic&db=mysql&ws=nginx

Since 5.0 it supports also Nginx

**Comment by jobetinfosec** [comment]
@jaapmarcus 

You're right, I'll try that!

Thanks for your support!

Best regards

**Comment by nerv55** [comment]
Thanks for support.

**Comment by mckaygerhard** [comment]
here comes with a partial solution event said "that user are abusive",, **i found the solution.. sad due**  i concluden will not uses hestia.. cos causes many troubles on updates that ispconfig does not:

@jobetinfosec  pointed that libxml2 are the main problem.. that packages comes from you @oerdnj  from sury repos.. 

```
root@srv1:~# apt-cache show libxml2 | grep Version
Version: 2.9.9+dfsg-1+0~20200226.5+debian9~1.gbp3b6674
Version: 2.9.4+dfsg1-2.2+deb9u2
```

@jaapmarcus  i've managed to make the package pass the bug, the problem with you is that you don't use security jumps/pinning (i guess so many security check are not need because we are using NON-OFFICIAL repositories, and taking in consideration the response of sury that oldstable packages has no priority!!!!!) i understand that these repos like sury's change things and don't coordinate with the old ones from oldstable and oldoldstable.. that why ! ok! if you doub that check issues!

an ugly answer is "use unstable or use the latest version" and we are with Debian 8 and Debian 9... hence the problem

In debian 8 packages causes a lot of troubles.. due use varios versions os libssl and openssl
In debian 9 packages has some minor conflicts

my firts partial solution are that:

```
cat > /etc/apt/apt.conf.d/50venenuxcustom << EOF
APT::Get::AllowUnauthenticated "true";
Acquire::AllowInsecureRepositories "true";
Acquire::AllowDowngradeToInsecureRepositories "true";
Acquire::Check-Valid-Until "false";
EOF
```

**alfter that partial solucion are pinning onf the conflicts @jobetinfosec @ScIT-Raphael you can do all of thos "insecure" customized thing during install and later erased the files customized and nothings happened and libxml2 package problem are solved BUT: now comes the problem with multiphp packages.. some have missing depends.. so conclusion.. sury packages problem**  so only can install one php version.. and no all the packages.. 

PD: for those that need lighttpd support with php updated packages venenux seem provides non.conflicting packages for! https://github.com/oerdnj/deb.sury.org/issues/1056 but repository will be updated!

**Comment by Lupul** [comment]
@mckaygerhard **the problem reported here is not `sury` packages** but a BUG in the Hestia installer (both master and release) which I have introduced with this commit https://github.com/hestiacp/hestiacp/commit/9eac550892bd98ea6879b07279a37f449ce2fd31 and will push a fix for it soon, so it you want someone to blame, here I am :raising_hand:

PS: I can't understand this aggressive attitude,  @ScIT-Raphael has already investigated and confirmed this issue in a couple of hours after being reported. This lack o patience is not at all constructive.

**Comment by ghost** [comment]
@mckaygerhard I'm sorry to hear that you've encountered this issue, but please consider that this is open-source software that we work on in our own time, and unfortunately things can break occasionally. We're only human after all.

To add to @Lupul's statement, let's keep the feedback constructive and friendly here please. There's absolutely no need for bashing, and it will not be tolerated.

Thank you.

**Comment by mckaygerhard** [comment]
glad to hear all of us @Lupul and @ScIT-Raphael  and @kristankenney .. **event BLOCK THE USERS! ..  :+1:** 

currently i noted that! but also! but a simple miss: php multi choose, have problems in debian 8.. and 9 if you use multi php packages! maybe i must split the issue but same errors happened if you choose multi php packages.. 

thanks for support! of course i waith the fix.. **(i already fixed) but the comment and actitude of the sury owner** was so huge different from you guys! great work!

in any case we do not use anymore hestia! sorry .. and keep the good work!

**Comment by mckaygerhard** [comment]
-> PD: _"This lack o patience is not at all constructive."_ the common reponse are "we are free software, you are on your own".. do you understand that in a pressure moment  your software that means will not fail suddendly fails.  ans we before post and issue: search and search to keep sure are not own error?_

mantain a piece of software are difficult and needs time of manpower involved! but also you guys must assume that are a conpromised assumed! 

i collaborate in manny projects and if i do a kind of support i will not put as answers "we are software collaborative.. you are on your own!"  i posted a very similar bug (maybe different in deep) but with similar outputs.. many users simply don't post the issue just because they know they will be with answered like that! they are fed up with it! using the software is also collaborating! without the users there's no reason of usage and development! of course we need money but also we need feedback!

**Comment by ghost** [comment]
@mckaygerhard, our core team is a small team of people scattered across the world and we work on this project in the time that we have available; we all have other obligations outside of Hestia. We work on this project partly for our enjoyment, or because we have a use case for the product ourselves personally or as part of our own businesses.

Hestia Control Panel is provided with absolutely no warranties or guarantees, at no cost to you, and we do what we can to provide best effort support. No, it won't always be instant and again, we're only human. This really has nothing to do with it being an open source project; we're more than willing to collaborate with our users, fix issues when they arise and accommodate feature requests, however like any other development project all of this has to be done in a constructive manner.

**Comment by Lupul** [comment]
Installer should be fixed now when using `--nginx no`, tested successfully clean install.
(still complains about /etc/rc.local but it's just cosmetic, can be ignored)

**Comment by mckaygerhard** [comment]
thanks to all.. remenber that still have problems with multiphp option..

**Comment by Lupul** [comment]
Tested the multiphp earlier but on ubuntu 18.04, will do a debian9 test with:
```
--apache yes --nginx no --phpfpm yes --multiphp no --postgresql yes --mysql yes --quota yes
```

**Comment by Lupul** [comment]
Just finished two clean install tests from release branch on debian9 and everything worked fine (changing php versions on web domains, removing and adding them back, phpinfo etc)

test1: `--apache yes --nginx no --phpfpm yes --multiphp no --postgresql yes --mysql yes --quota yes --force --interactive no --clamav no`
test2: `--apache yes --nginx no --phpfpm yes --multiphp yes --postgresql yes --mysql yes --quota yes --force --interactive no --clamav no`

If you still have difficulties with multi-php, open a new issue (with install logs) and we will take a look.
